name: msds2025ft-ml3-transformers
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - matplotlib=3.9.4
  - pandas=2.2.3
  - ipykernel=6.29.5
  - notebook
  - python=3.9
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - pip=25.1.1
  - scipy=1.13.1
  - openpyxl=3.1.5
  - numpy=1.26.4
  - pip:
    - ipywidgets==8.1.7
    - pydot==1.4.2
    - tensorflow==2.16.1
    - keras==3.3.3
Then reopen PowerShell